---
name: Expo Preview Action
author: Expo
description: Expo CLI in your GitHub Actions workflow.
branding:
  icon: upload-cloud
  color: gray-dark
runs:
  using: node12
  main: build/index.js
inputs:
  channel:
    description: The name of the update channel
    required: true
  scheme:
    description: The deep link scheme
    required: false
  project-flavor:
    description: The type of your project. Available options `development-client` or `expo-go
    required: false
  project-root:
    description: The path to the folder containing `package.json`
    required: false
  expo-cli-path:
    description: The path to the expo-cli
    required: false
  android-manifest-path:
    description: The path to the `AndroidManifest.xml`
    required: false
  ios-info-plist-path:
    description: The path to the `Info.plist`
    required: false
  token:
    description: >
      GitHub token for GitHub API requests.
      You shouldn't need to set this themselves, but we recommend using a service account with the least permissions necessary if you want to do it.
      [Learn more about creating and using encrypted secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    default: ${{ github.token }}
    required: true
